/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IamBossRouteImport } from './routes/IamBoss'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EducationWhatIsCitizenJournalismRouteImport } from './routes/education.what-is-citizen-journalism'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksIndiaCoverageRouteImport } from './routes/api/public/hooks/india-coverage'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IamBossRoute = IamBossRouteImport.update({
  id: '/IamBoss',
  path: '/IamBoss',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationWhatIsCitizenJournalismRoute =
  EducationWhatIsCitizenJournalismRouteImport.update({
    id: '/education/what-is-citizen-journalism',
    path: '/education/what-is-citizen-journalism',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksIndiaCoverageRoute =
  ApiPublicHooksIndiaCoverageRouteImport.update({
    id: '/api/public/hooks/india-coverage',
    path: '/api/public/hooks/india-coverage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/IamBoss': typeof IamBossRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/article/$id': typeof ArticleIdRoute
  '/education/what-is-citizen-journalism': typeof EducationWhatIsCitizenJournalismRoute
  '/api/public/hooks/india-coverage': typeof ApiPublicHooksIndiaCoverageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/IamBoss': typeof IamBossRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/article/$id': typeof ArticleIdRoute
  '/education/what-is-citizen-journalism': typeof EducationWhatIsCitizenJournalismRoute
  '/api/public/hooks/india-coverage': typeof ApiPublicHooksIndiaCoverageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/IamBoss': typeof IamBossRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/article/$id': typeof ArticleIdRoute
  '/education/what-is-citizen-journalism': typeof EducationWhatIsCitizenJournalismRoute
  '/api/public/hooks/india-coverage': typeof ApiPublicHooksIndiaCoverageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/IamBoss'
    | '/contact'
    | '/sitemap.xml'
    | '/submit'
    | '/admin'
    | '/article/$id'
    | '/education/what-is-citizen-journalism'
    | '/api/public/hooks/india-coverage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/IamBoss'
    | '/contact'
    | '/sitemap.xml'
    | '/submit'
    | '/admin'
    | '/article/$id'
    | '/education/what-is-citizen-journalism'
    | '/api/public/hooks/india-coverage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/IamBoss'
    | '/contact'
    | '/sitemap.xml'
    | '/submit'
    | '/_authenticated/admin'
    | '/article/$id'
    | '/education/what-is-citizen-journalism'
    | '/api/public/hooks/india-coverage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  IamBossRoute: typeof IamBossRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  ArticleIdRoute: typeof ArticleIdRoute
  EducationWhatIsCitizenJournalismRoute: typeof EducationWhatIsCitizenJournalismRoute
  ApiPublicHooksIndiaCoverageRoute: typeof ApiPublicHooksIndiaCoverageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/IamBoss': {
      id: '/IamBoss'
      path: '/IamBoss'
      fullPath: '/IamBoss'
      preLoaderRoute: typeof IamBossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/what-is-citizen-journalism': {
      id: '/education/what-is-citizen-journalism'
      path: '/education/what-is-citizen-journalism'
      fullPath: '/education/what-is-citizen-journalism'
      preLoaderRoute: typeof EducationWhatIsCitizenJournalismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/india-coverage': {
      id: '/api/public/hooks/india-coverage'
      path: '/api/public/hooks/india-coverage'
      fullPath: '/api/public/hooks/india-coverage'
      preLoaderRoute: typeof ApiPublicHooksIndiaCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  IamBossRoute: IamBossRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  ArticleIdRoute: ArticleIdRoute,
  EducationWhatIsCitizenJournalismRoute: EducationWhatIsCitizenJournalismRoute,
  ApiPublicHooksIndiaCoverageRoute: ApiPublicHooksIndiaCoverageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
